name: woocommerce_api
description: A package to interact with the WooCommerce API (null-safe).
version: 0.2.0
author: Samarth Agarwal <samarthagarwal@live.com>
homepage: https://github.com/samarthagarwal/woocommerce_dart

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: '>=3.4.0 <4.0.0'
